AppsPortal/Areas/AHD/Controllers/InternationalStaffPresenceTrackingController.cs
using AHD_DAL.Model;
using AHD_DAL.ViewModels;
using AppsPortal.BaseControllers;
using AppsPortal.Extensions;
using AppsPortal.Library;
using AppsPortal.Models;
using AppsPortal.ViewModels;
using AutoMapper;
using OfficeOpenXml;
using RES_Repo.Globalization;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace AppsPortal.Areas.AHD.Controllers
{
    public class InternationalStaffPresenceTrackingController : AHDBaseController
    {
        // GET: AHD/InternationalStaffPresenceTracking
        public ActionResult Index()
        {
            return View();
        }
        [Route("AHD/StaffPresenceTrackingIndex/")]
        public ActionResult StaffPresenceTrackingIndex()
        {
            //if (!cms.hasaction(permissions.internationalstaffattendancepresence.access, apps.ahd))
            //{
            //    return json(dbahd.permissionerror());
            //}

            return View("~/Areas/AHD/Views/InternationalStaffPresenceTracking/Index.cshtml");
        }
        [HttpPost]
        public ActionResult GetWorkingDay()
        {
            var _user = DbCMS.StaffCoreData.Where(x => x.UserGUID == UserGUID).FirstOrDefault();
            Guid DutyStationConfigurationGUID = DbCMS.codeDutyStationsConfigurations.Where(x => x.DutyStationGUID == _user.DutyStationGUID).FirstOrDefault().DutyStationConfigurationGUID;

            var WorkingDay = (from a in DbCMS.codeWorkingDaysConfigurations.Where(x => x.Active && x.DutyStationConfigurationGUID == DutyStationConfigurationGUID)
                              join b in DbCMS.codeTablesValues on a.DayGUID equals b.ValueGUID
                              select new WorkDay { Day = b.SortID.Value }).ToList();
            return Json(new JsonReturn { WorkDays = WorkingDay });
        }


        [HttpPost]
        public ActionResult GetCalendarDataFromDatabase(DateTime start, DateTime end)
        {
            //Access is authorized by Access Action Department
            //List<string> AuthorizedListDepartment = DbCMS.userPermissions.Where(x => x.Active && x.ActionGUID == Permissions.AppointmentType.AccessGuid && x.UserProfileGUID == UserProfileGUID).Select(x => x.FactorsToken).Distinct().ToList();
            ////Access is authorized by Access Action DutyStation
            //List<string> AuthorizedListDutyStation = DbCMS.userPermissions.Where(x => x.Active && x.ActionGUID == Permissions.InternationalStaffAttendancePresence.AccessGuid && x.UserProfileGUID == UserProfileGUID).Select(x => x.FactorsToken).Distinct().ToList();

            var userProfiles = DbCMS.userProfiles.Where(x => x.UserProfileGUID == UserProfileGUID).FirstOrDefault();
            var Events = (from a in DbAHD.dataInternationalStaffAttendance
                          .Where(x => x.FromDate >= start && x.ToDate <= end && x.Active).ToList()
                              //.Where(x => AuthorizedListDepartment.Contains(x.codeAppointmentType.DepartmentGUID.ToString()))
                              //.Where(x => AuthorizedListDutyStation.Contains(x.DutyStationGUID.ToString()))
                          join b in DbAHD.codeAHDInternationalStaffAttendanceType.Where(x => x.Active) on a.InternationalStaffAttendanceTypeGUID equals b.InternationalStaffAttendanceTypeGUID into LJ1
                          from R1 in LJ1.DefaultIfEmpty()
                          select new CalendarEvents
                          {
                              EventId = a.InternationalStaffAttendanceGUID,
                              UserGUID = a.StaffGUID,
                              EventStartDate = a.FromDate,
                              EventEndDate = a.ToDate.Value.AddDays(1),
                              Title = a.StaffName + " " + R1.AttendanceTypeName,
                              EventDescription = a.Comments,
                              AllDayEvent = false,

                              backgroundColor = R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.AnnualLeave ? "#0066CC" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.RR ? "#FF3355" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.UncerticSickLeave ? "#8133FF" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.CertificatedSickLeave ? "#FFB833" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.SLWFP ? "#42d1f5" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.TravelTime ? "#44bcd8" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.OfficialHoliday ? "#33FFBD" :
                                  R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.Mission ? "#707339" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.Quarantine ? "#6bafe3" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.FamilyLeave ? "#fcba03" :
                                R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.HomeLeave ? "#a89b32" :
                                R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.PaternityLeave ? "#34a832" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.TravelPurpose ? "#a89ba2" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.Weekend ? "#945142" :

                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.TeleCommuniting ? "#FFBD33" : "",

                              borderColor = R1.InternationalStaffAttendanceTypeGUID.ToString() == "13afca94-4fa0-479a-85db-8aef4bc64cbb" ? "#00c0ef" : "#00c0ef",


                          }).ToList();
            return Json(new { CalendarEvents = Events }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult GetCalendarDataFromDatabaseStaffFilter(Guid filterGUID)
        {
            //Access is authorized by Access Action Department
            //List<string> AuthorizedListDepartment = DbCMS.userPermissions.Where(x => x.Active && x.ActionGUID == Permissions.AppointmentType.AccessGuid && x.UserProfileGUID == UserProfileGUID).Select(x => x.FactorsToken).Distinct().ToList();
            ////Access is authorized by Access Action DutyStation
            //List<string> AuthorizedListDutyStation = DbCMS.userPermissions.Where(x => x.Active && x.ActionGUID == Permissions.InternationalStaffAttendancePresence.AccessGuid && x.UserProfileGUID == UserProfileGUID).Select(x => x.FactorsToken).Distinct().ToList();

            var userProfiles = DbCMS.userProfiles.Where(x => x.UserProfileGUID == UserProfileGUID).FirstOrDefault();
            var Events = (from a in DbAHD.dataInternationalStaffAttendance
                          .Where(x => x.Active && x.StaffGUID == filterGUID).ToList()
                              //.Where(x => AuthorizedListDepartment.Contains(x.codeAppointmentType.DepartmentGUID.ToString()))
                              //.Where(x => AuthorizedListDutyStation.Contains(x.DutyStationGUID.ToString()))
                          join b in DbAHD.codeAHDInternationalStaffAttendanceType.Where(x => x.Active) on a.InternationalStaffAttendanceTypeGUID equals b.InternationalStaffAttendanceTypeGUID into LJ1
                          from R1 in LJ1.DefaultIfEmpty()
                          select new CalendarEvents
                          {
                              EventId = a.InternationalStaffAttendanceGUID,
                              UserGUID = a.StaffGUID,
                              EventStartDate = a.FromDate,
                              EventEndDate = a.ToDate.Value.AddDays(1),
                              Title = a.StaffName + " " + R1.AttendanceTypeName,
                              EventDescription = a.Comments,
                              AllDayEvent = false,
                              backgroundColor = R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.AnnualLeave ? "#0066CC" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.RR ? "#FF3355" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.UncerticSickLeave ? "#8133FF" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.CertificatedSickLeave ? "#FFB833" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.SLWFP ? "#42d1f5" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.TravelTime ? "#44bcd8" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.OfficialHoliday ? "#33FFBD" :
                              R1.InternationalStaffAttendanceTypeGUID == coddeInternationalStaffAttendanceTypeAttendanceTable.Weekend ? "#945142" :

AppsPortal/Areas/AHD/Views/InternationalStaffPresenceTracking/_StaffLeaveModal.cshtml
@model InternationalStaffPresenceAttendanceUpdateModel
@using (Html.BeginForm("AttendanceLeaveCalendar", "InternationalStaffPresenceTracking", new { Area = "AHD" }, FormMethod.Post, new { id = "StaffLeaveForm" }))
{
    string ModalTitle = Model.InternationalStaffAttendanceGUID.ToString() == Guid.Empty.ToString() ? "New Leave" : "Edit Leave";
    @Html.Partial("_ModalHeader", ModalTitle)
<div class="modal-body">
    @*@Html.AntiForgeryToken()*@
    @Html.FormHiddenFields(model => model.InternationalStaffAttendanceGUID)
    @Html.HiddenFor(model => model.CreatedByGUID)
    @Html.HiddenFor(model => model.CreateDate)
    @Html.HiddenFor(model => model.StaffName)
    @Html.HiddenFor(model => model.PositionName)
  
    <div class="form-group">

        @Html.LabelFor(model => model.StaffGUID)
        @Html.DropDownListFor(model => model.StaffGUID, new DropDownList().InternationalStaffUsers(true), "", new
                    {
                    @class = "form-control select2-basic-search",
                    style = "width:100%",

                    })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.InternationalStaffAttendanceTypeGUID, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.InternationalStaffAttendanceTypeGUID, new DropDownList().AHDInternationalAttendanceTypes(), "", new
   {
       style = "width:100%",
       @class = "form-control select2-basic-search"
   })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.FromDate)
        @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ToDate)
        @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
    </div>
    <div class="form-group">

        @Html.LabelFor(model => model.CountryGUID)
        @Html.DropDownListFor(model => model.CountryGUID, new DropDownList().Countries(), "", new
                    {
                    @class = "form-control select2-basic-search",
                    style = "width:100%",

                    })
    </div>

    @*<div class="form-group">

        @Html.LabelFor(model => model.CityGUID)
        @Html.DropDownListFor(model => model.CityGUID, new DropDownList().Countries(), "", new
                    {
                    @class = "form-control select2-basic-search",
                    style = "width:100%",

                    })
    </div>*@


    <div class="form-group">
        @Html.LabelFor(model => model.LeaveLocation)
        @Html.EditorFor(model => model.LeaveLocation, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comments)
        @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
    </div>
</div>
    <div class="modal-footer form-footer">
        @if (Model.InternationalStaffAttendanceGUID == Guid.Empty)
        {
            @Html.CreateButton(Permissions.InternationalStaffAttendancePresence.Create, Apps.AHD)
        }
        else
        {
            if (Model.Active)
            {
                @Html.UpdateButton(Permissions.InternationalStaffAttendancePresence.Update, Apps.AHD)
                @Html.DeleteSwitchButton(Permissions.InternationalStaffAttendancePresence.Delete, Apps.AHD)
            }
            else
            {
                @Html.RestoreSwitchButton(Permissions.InternationalStaffAttendancePresence.Delete, Apps.AHD)
            }
        }
        @Html.CloseModalButton()
    </div>
}