AppsPortal/Areas/AMS/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AMS_DAL.Model;
using AppsPortal.AMS.ViewModels;
using AppsPortal.Areas.AMS.Rdlc;
using AppsPortal.Areas.AMS.Rdlc.AMSDataSetTableAdapters;
using AppsPortal.BaseControllers;
using AppsPortal.Library;
using Microsoft.Reporting.WebForms;


namespace AppsPortal.Areas.AMS.Controllers
{
    public class ReportsController : AMSBaseController
    {
        // GET: AMS/Reports

        #region Appointments Slip
        public void AppointmentsSlip(Guid PK)
        {
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.ZoomMode = ZoomMode.Percent;
            reportViewer.ZoomPercent = 90;
            reportViewer.Width = System.Web.UI.WebControls.Unit.Pixel(850);
            reportViewer.Height = System.Web.UI.WebControls.Unit.Pixel(600);

            reportViewer.AsyncRendering = true;
            reportViewer.LocalReport.DataSources.Clear();
            var appointment = DbAMS.dataAppointment.Where(x => x.AppointmentGUID == PK).FirstOrDefault();
            RP_AppointmentSlepTableAdapter appointmentsSlipTableAdapter = new RP_AppointmentSlepTableAdapter();
            AMSDataSet amsDataSet = new AMSDataSet();
            appointmentsSlipTableAdapter.Fill(amsDataSet.RP_AppointmentSlep, PK, LAN);
            ReportDataSource reportDataSource = new ReportDataSource("AppointmentsSlip", amsDataSet.Tables["RP_AppointmentSlep"]);
            reportViewer.LocalReport.DataSources.Add(reportDataSource);
            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Areas/AMS/Rdlc/AppointmentsSlip\"+appointment.DutyStationGUID+".rdlc";
           // ViewBag.ReportViewer = reportViewer;
            Warning[] warnings;
            string[] streamIds;
            string contentType;
            string encoding;
            string extension;

            //Export the RDLC Report to Byte Array.
            byte[] bytes = reportViewer.LocalReport.Render("PDF", null, out contentType, out encoding, out extension, out streamIds, out warnings);

            //Download the RDLC Report in Word, Excel, PDF and Image formats.
            Response.Clear();
            Response.Buffer = true;
            Response.Charset = "";
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.ContentType = contentType;
            Response.AppendHeader("Content-Disposition", "attachment; filename=RDLC." + extension);
            Response.BinaryWrite(bytes);
            Response.Flush();
            Response.End();
           // return PartialView("~/Areas/AMS/Views/Reports/_AppointmentsSlip.cshtml");

        }
        #endregion

        #region Reports Board

        [HttpGet]
        public ActionResult SchedularReport()
        {
            Guid UNHCR = Guid.Parse("E156C022-EC72-4A5A-BE09-163BD85C68EF");
            return View("~/Areas/AMS/Views/Reports/SchedularReports.cshtml",new ReportParametersList() { OrganizationInstanceGUID=UNHCR});
        }

        [HttpPost]
        public ActionResult ReportsBoard(int Report, DateTime? EndDate, DateTime? StartDate, Guid? DepartmentGUID)
        {
            if (StartDate == null) { StartDate = new DateTime(DateTime.Now.Year, 1, 1); }
            if (EndDate == null) { EndDate = DateTime.Now; }
            string URL = "LoadUrl('ReportViewer','../Reports/ReportsBoardLoad?Report=" + Report +
                "&EndDate=" + EndDate.Value.Ticks +
                "&StartDate=" + StartDate.Value.Ticks +
                "&DepartmentGUID=" + DepartmentGUID  + "')";
            return Json(DbCMS.SingleUpdateMessage(null, null, null, URL, "Please Wait...."));
        }

        public ActionResult ReportsBoardLoad(int Report, long? EndDate, long? StartDate, string DepartmentGUID)
        {
            string FileType = "";
            string[] FilesRDLC = new string[] {
            "AppointmentByDate",
            "AppointmentByExecutionTime",
            "AppointmentOverview",
            "AppointmentSlots",
            };
            ReportViewer reportViewer = new ReportViewer();
            reportViewer.ProcessingMode = ProcessingMode.Local;
            reportViewer.ZoomMode = ZoomMode.Percent;
            reportViewer.ZoomPercent = 100;
            reportViewer.Width = System.Web.UI.WebControls.Unit.Percentage(900);
            reportViewer.Height = System.Web.UI.WebControls.Unit.Pixel(600);

            reportViewer.AsyncRendering = true;
            reportViewer.LocalReport.DataSources.Clear();
            ReportDataSource reportDataSource = new ReportDataSource();
            string ReportName = FilesRDLC[Report];
            Guid DutyStationGUID = DbAMS.StaffCoreData.Where(x => x.UserGUID == UserGUID).FirstOrDefault().DutyStationGUID;

            if (ReportName.StartsWith("AppointmentByDate"))
            {
                FileType = "Excel";
                RP_AppointmentByDateTableAdapter AppointmentByDate = new RP_AppointmentByDateTableAdapter();
                AMSDataSet amsDataSet = new AMSDataSet();
                AppointmentByDate.Fill(amsDataSet.RP_AppointmentByDate,
                    Guid.Parse( DepartmentGUID),
                    new DateTime( StartDate.Value),
                    new DateTime(EndDate.Value)
                    , LAN,
                    DutyStationGUID);
                 reportDataSource = new ReportDataSource("AppointmentByDate", amsDataSet.Tables["RP_AppointmentByDate"]);
            }
            if (ReportName.StartsWith("AppointmentSlots"))
            {
                FileType = "Excel";
                RP_AppointmentSlotsTableAdapter AppointmentSlots = new RP_AppointmentSlotsTableAdapter();
                AMSDataSet amsDataSet = new AMSDataSet();
                AppointmentSlots.Fill(amsDataSet.RP_AppointmentSlots,
                    Guid.Parse(DepartmentGUID),
                    DutyStationGUID,
                   new DateTime(StartDate.Value),
                    new DateTime(EndDate.Value)
                    , LAN);
                reportDataSource = new ReportDataSource("AppointmentSlots", amsDataSet.Tables["RP_AppointmentSlots"]);
            }
            if (ReportName.StartsWith("AppointmentOverview"))
            {
                FileType = "Excel";
                RP_AppointmentOverviewTableAdapter AppointmentOverview = new RP_AppointmentOverviewTableAdapter();
                AMSDataSet amsDataSet = new AMSDataSet();
                AppointmentOverview.Fill(amsDataSet.RP_AppointmentOverview,
                   new DateTime(StartDate.Value),
                    new DateTime(EndDate.Value)
                    ,LAN
                    ,DutyStationGUID);
                reportDataSource = new ReportDataSource("AppointmentOverview", amsDataSet.Tables["RP_AppointmentOverview"]);
            }
            if (ReportName.StartsWith("AppointmentByExecutionTime"))
            {
                FileType = "Excel";
                RP_AppointmentByExecutionTimeTableAdapter AppointmentByExecutionTime = new RP_AppointmentByExecutionTimeTableAdapter();

                AMSDataSet amsDataSet = new AMSDataSet();
                AppointmentByExecutionTime.Fill(amsDataSet.RP_AppointmentByExecutionTime,
                    Guid.Parse(DepartmentGUID),

                    new DateTime(StartDate.Value),
                    new DateTime(EndDate.Value)
                    ,LAN
                    ,DutyStationGUID);
                reportDataSource = new ReportDataSource("AppointmentByExecutionTime", amsDataSet.Tables["RP_AppointmentByExecutionTime"]);
            }
            reportViewer.LocalReport.DataSources.Add(reportDataSource);
            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Areas/AMS/Rdlc\" + ReportName + ".rdlc";

            Warning[] warnings;
            string[] streamIds;
            string contentType;
            string encoding;
            string extension;


            //Export the RDLC Report to Byte Array.
            byte[] bytes = reportViewer.LocalReport.Render(FileType, null, out contentType, out encoding, out extension, out streamIds, out warnings);


            //this.Response.ClearContent();
            //this.Response.ClearHeaders();
            //this.Response.Clear();
            //this.Response.AddHeader("content-disposition", "attachment; filename= " + ReportName + "." + extension);
            //this.Response.ContentType = "Application/" + FileType;
            //this.Response.BinaryWrite(bytes);
            //this.Response.Flush();
            //this.Response.End();
            ViewBag.ReportViewer = reportViewer;
            return PartialView("~/Areas/DAS/Views/Reports/_Report.cshtml");
        }

        #endregion

       

      

   

      


    }
}

AppsPortal/Areas/GTP/Controllers/ReportsController.cs
using AppsPortal.BaseControllers;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppsPortal.Areas.GTP.Controllers
{
    public class ReportsController : GTPBaseController
    {
        // GET: GTP/Reports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DownloadSuccessfulApplicantsReport()
        {
            string sourceFile = Server.MapPath("~/Areas/GTP/ReportsTemplates/Record of successful applicants.xlsx");

            string receiptFileName = "Record of successful applicants" + DateTime.Now.ToBinary() + ".xlsx";

            string DisFolder = Server.MapPath("~/Areas/GTP/GeneratedReports/" + receiptFileName);

            System.IO.File.Copy(sourceFile, DisFolder);

            var reportData = (from a in DbGTP.dataGTPApplications
                              join b in DbGTP.codeGTPCategories on a.GTPCategoryGUID equals b.GTPCategoryGUID
                              join c in DbGTP.userPersonalDetailsLanguages on a.UserGUID equals c.UserGUID
                              join d in DbGTP.userServiceHistories on a.UserGUID equals d.UserGUID
                              where c.LanguageID == "EN" && c.Active && d.Active && (a.IsEligible.HasValue && a.IsEligible.Value == true)
                              select new
                              {
                                  c.Surname,
                                  c.FirstName,
                                  d.EmailAddress,
                                  a.ReviewedOn,
                                  b.GTPCategoryDescription,
                                  a.GTPApplicationEligibleAs,
                                  a.GTPApplicationExpiryDate

                              }).ToList();
            using (var package = new ExcelPackage(new FileInfo(DisFolder)))
            {
                ExcelWorksheet worksheet = package.Workbook.Worksheets[1];
                int i = 3;
                foreach (var record in reportData)
                {
                    worksheet.Cells["A" + i].Value = record.Surname;
                    worksheet.Cells["B" + i].Value = record.FirstName;
                    worksheet.Cells["C" + i].Value = record.EmailAddress;
                    worksheet.Cells["D" + i].Value = record.ReviewedOn.Value.ToShortDateString();
                    worksheet.Cells["E" + i].Value = record.GTPCategoryDescription;
                    worksheet.Cells["F" + i].Value = record.GTPApplicationEligibleAs.Value.ToShortDateString();
                    worksheet.Cells["G" + i].Value = record.GTPApplicationExpiryDate.Value.ToShortDateString();
                    i++;
                }

                worksheet.Column(1).AutoFit();
                worksheet.Column(2).AutoFit();
                worksheet.Column(3).AutoFit();
                worksheet.Column(4).AutoFit();
                worksheet.Column(5).AutoFit();
                worksheet.Column(6).AutoFit();
                worksheet.Column(7).AutoFit();

                package.Save();
            }
            byte[] fileBytes = System.IO.File.ReadAllBytes(@"" + DisFolder + "");
            return File(fileBytes, "application/octet-stream", "Record of successful applicants.xlsx");
        }
    }
}

AppsPortal/Areas/RMS/Controllers/ReportsController.cs
using AppsPortal.BaseControllers;
using Microsoft.Reporting.WebForms;
using RMS_DAL.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AppsPortal.Areas.RMS.Controllers
{
    public class ReportsController : RMSBaseController
    {

        [HttpGet]
        public ActionResult ReportIndex()
        {

            return View("~/Areas/RMS/Views/Reports/ReportIndex.cshtml", new RMSReportParametersList());
        }

        #region Charts
        [HttpGet]
        public ActionResult Chart()
        {
            ReportViewer reportViewer = new ReportViewer();
            ViewBag.ReportViewer = reportViewer;
            return View("~/Areas/RMS/Views/Reports/Charts.cshtml", new RMSReportParametersList());
        }
        class HieghChartReport
        {
            public List< series> MainReport { get; set; }
        }
        class series
        {
            public string name { set; get; }
            public double[] data { get; set; }
        }


        
        [HttpPost]
        public ActionResult chart(RMSReportParametersList rp)
        {
            var MainData = (from a in DbRMS.dataPrinterLog.AsEnumerable().Where(x => x.LogDateTime>=rp.LogDateTimeStart && x.LogDateTime<=rp.LogDateTimeEnd && x.PrinterConfigurationGUID == rp.PrinterConfigurationGUID && rp.OidGUID.Contains(x.OidGUID))
                            join b in DbRMS.codeOID on a.OidGUID equals b.OidGUID
                            orderby a.LogDateTime
                            group new
                            {
                                b.OIDDescription,
                                a.LogDateTime,
                                a.OidValue
                            } by b.OIDDescription into G
                          
                            select
                            new series
                            {
                                name = G.Key,
                                data = (from x in G select  Convert.ToDouble(x.OidValue) ).ToArray()
                            }).ToList();

            return Json(new HieghChartReport { MainReport= MainData}, JsonRequestBehavior.AllowGet);
        }
      
        #endregion
    }
}

AppsPortal/Areas/PPA/Views/Reports/ProgressTrackingReport/_PPAProgresReportOriginaFiles.cshtml
@model List<ProgressTrackingReportOriginalFilesModel>

<div class="panel-group portalConfig overrideEnabled" id="accordionLVL2" role="tablist" aria-multiselectable="true">

    @foreach (var item in Model)
    {
    <div class="panel panel-default">

        <div class="panel-heading" role="tab" id="CountriesHeader" data-url="@Url.Action("GetPPAFilesHistory","Reports",new {Area = "PPA", FK =  item.PPAOriginalFileGUID})" data-toggle="collapse" data-parent="#accordionLVL2" href="#@item.PPAOriginalFileGUID" aria-expanded="false">
            <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL2" href="#@item.PPAOriginalFileGUID">
                <table style="width:100%">
                    <tbody>
                        <tr style="width:100%;">
                            <td style="width:10%;"><b>File Name:</b></td>
                            <td style="width:80%;"><b>@item.FileName</b></td>
                        </tr>
                        <tr style="width:100%;">
                            <td style="width:20%;">File Category:</td>
                            <td style="width:80%;">@item.PPAFileCategoryDescription</td>
                        </tr>
                        <tr style="width:100%;">
                            <td style="width:20%;">Upload Date:</td>
                            <td style="width:80%;">@item.UploadDate</td>
                        </tr>
                    </tbody>
                </table>
            </span>
        </div>
        <div id="@item.PPAOriginalFileGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
            <div class="panel-body">

                @*<div class="panel-group portalConfig overrideEnabled" id="accordionLVL3" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL3" href="#someParamGUID" aria-expanded="false">
                            <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL3" href="#someParamGUID">
                                @@FileActionByUserName
                            </span>
                        </div>
                        <div id="someParamGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                            <div class="panel-body">
                                <div class="panel-group portalConfig overrideEnabled" id="accordionLVL4" role="tablist" aria-multiselectable="true">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL4" href="#PPAFileVersionGUID" aria-expanded="false">
                                            <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL4" href="#PPAFileVersionGUID">
                                                Downloaded original version on:
                                                <br />
                                                Uploaded version:

                                            </span>
                                        </div>
                                        <div id="PPAFileVersionGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                                            <div class="panel-body">
                                                more details will be here soon.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>*@


            </div>
        </div>
    </div>
    }


    @*<div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL2" href="#originalFilePPAOriginalFileGUID" aria-expanded="false">
            <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL2" href="#originalFilePPAOriginalFileGUID">
                @@originalFile.FileName
            </span>
        </div>*@
    @*<div id="originalFilePPAOriginalFileGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
            <div class="panel-body">
                <div class="panel-group portalConfig overrideEnabled" id="accordionLVL3" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL3" href="#someParamGUID" aria-expanded="false">
                            <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL3" href="#someParamGUID">
                                @@FileActionByUserName
                            </span>
                        </div>
                        <div id="someParamGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                            <div class="panel-body">
                                <div class="panel-group portalConfig overrideEnabled" id="accordionLVL4" role="tablist" aria-multiselectable="true">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL4" href="#PPAFileVersionGUID" aria-expanded="false">
                                            <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL4" href="#PPAFileVersionGUID">
                                                Downloaded original version on:
                                                <br />
                                                Uploaded version:

                                            </span>
                                        </div>
                                        <div id="PPAFileVersionGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                                            <div class="panel-body">
                                                more details will be here soon.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@

</div>

AppsPortal/Areas/PPA/Views/Reports/ProgressTrackingReport/_PPAProgressReport.cshtml
@model List<PPAProgressTrackingReportModel>
@{
    PPA_DAL.Model.PPAEntities DbPPA = new PPAEntities();
}
<style>
    .padding-left-25 {
        padding-left: 25px !important;
    }

    .width-12 {
        width: 15% !important;
    }

    .padding-bot-10 {
        padding-bottom: 10px !important;
    }

    .padding-bot-5 {
        padding-bottom: 5px !important;
    }
</style>
<div class="panel-group portalConfig overrideEnabled" id="accordion" role="tablist" aria-multiselectable="true">

    @if (Model.Count == 0)
    {

    }
    @foreach (var ppaAgreement in Model)
    {
        int downloadersCount = 0;
        downloadersCount = (from a in DbPPA.PPAOriginalFile.Where(x => x.PPAGUID == ppaAgreement.PPAGUID)
                            join b in DbPPA.PPAFileVersion.Where(x => x.Active) on a.PPAOriginalFileGUID equals b.PPAOriginalFileGUID
                            where b.FileActionType == "Download"
                            select new
                            {
                                b.FileActionByUserGUID,
                                b.FileActionType
                            }).Distinct().Count();

        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="CountriesHeader" data-url="@Url.Action("GetPPAFiles","Reports",new {Area = "PPA", FK = @ppaAgreement.PPAGUID})" data-toggle="collapse" data-parent="#accordion" href="#@ppaAgreement.PPAGUID" aria-expanded="false">
                <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#@ppaAgreement.PPAGUID">
                    <div class="row">
                        <div class="col-md-12">
                            <table style="width:100%">
                                <tr>
                                    <td class="padding-bot-10" colspan="4"><b>@ppaAgreement.PPADescription</b></td>
                                </tr>
                                <tr>
                                    <td class="width-12">Implementing Partner:</td>
                                    <td class="padding-left-25">@ppaAgreement.OrganizationDescription</td>
                                </tr>
                                <tr>
                                    <td class="width-12">Area of implementation:</td>
                                    <td class="padding-left-25">@ppaAgreement.PPATypeDescription</td>
                                </tr>
                                <tr>
                                    <td class="width-12">Deadline for review:</td>
                                    <td class="padding-left-25">@ppaAgreement.PPADeadline</td>
                                </tr>

                                <tr>
                                    <td class="width-12">Uploaded by:</td>
                                    <td class="padding-left-25">@ppaAgreement.StaffName / @ppaAgreement.DepartmentDescription</td>
                                </tr>
                                <tr>
                                    <td class="width-12">Uploaded to:</td>
                                    <td class="padding-left-25">@ppaAgreement.UploadedToDepartment</td>
                                </tr>
                                <tr>
                                    <td class="width-12">Status:</td>
                                    <td class="padding-left-25"><a class="clickLinkClassToReplace" data-PPAGUID="@ppaAgreement.PPAGUID" href="javascript:void(0)">@downloadersCount of @ppaAgreement.UploadedToCount Downloaded the package (click for more details)</a></td>
                                </tr>
                            </table>
                        </div>
                    </div>



                </span>
            </div>
            <div id="@ppaAgreement.PPAGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                <div class="panel-body panel-body-accordion">
                    @resxPages.Loading
                    @*<div class="panel-group portalConfig overrideEnabled" id="accordionLVL2" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL2" href="#originalFilePPAOriginalFileGUID" aria-expanded="false">
                                    <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL2" href="#originalFilePPAOriginalFileGUID">
                                        @@originalFile.FileName
                                    </span>
                                </div>
                                <div id="originalFilePPAOriginalFileGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                                    <div class="panel-body">
                                        <div class="panel-group portalConfig overrideEnabled" id="accordionLVL3" role="tablist" aria-multiselectable="true">
                                            <div class="panel panel-default">
                                                <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL3" href="#someParamGUID" aria-expanded="false">
                                                    <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL3" href="#someParamGUID">
                                                        @@FileActionByUserName
                                                    </span>
                                                </div>
                                                <div id="someParamGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                                                    <div class="panel-body">
                                                        <div class="panel-group portalConfig overrideEnabled" id="accordionLVL4" role="tablist" aria-multiselectable="true">
                                                            <div class="panel panel-default">
                                                                <div class="panel-heading" role="tab" id="CountriesHeader" data-toggle="collapse" data-parent="#accordionLVL4" href="#PPAFileVersionGUID" aria-expanded="false">
                                                                    <span class="panel-title collapsed accordion-toggle" data-toggle="collapse" data-parent="#accordionLVL4" href="#PPAFileVersionGUID">
                                                                        Downloaded original version on:
                                                                        <br />
                                                                        Uploaded version:

                                                                    </span>
                                                                </div>
                                                                <div id="PPAFileVersionGUID" class="panel-collapse collapse" role="tabpanel" aria-labelledby="CountriesHeader">
                                                                    <div class="panel-body">
                                                                        more details will be here soon.
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>*@
                </div>
            </div>
        </div>
    }

</div>